/**
 * Copyright (c) 2017-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

module.exports = {
  'CS Core': [
    {
      type: 'category',
      label: 'Algorithms',
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Sorting',
          items: [
            {
              type: 'autogenerated',
              dirName: 'Algorithms/Sorting',
            },
          ],
        },
        {
          type: 'category',
          label: 'Backtracking',
          items: [
            {
              type: 'autogenerated',
              dirName: 'Algorithms/Backtracking',
            },
          ],
        },
        {
          type: 'category',
          label: 'Graph',
          items: [
            {
              type: 'autogenerated',
              dirName: 'Algorithms/Graph',
            },
          ],
        },
        {
          type: 'category',
          label: 'Dynamic Programming',
          items: [
            {
              type: 'category',
              label: 'Coordinate Based',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'Algorithms/DynamicProgramming/Coordinate',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Sliding Window',
          items: [
            {
              type: 'autogenerated',
              dirName: 'Algorithms/SlidingWindow',
            },
          ],
        },
        {
          type: 'category',
          label: 'Interval',
          items: [
            {
              type: 'autogenerated',
              dirName: 'Algorithms/Interval',
            },
          ],
        },
        {
          type: 'category',
          label: 'Bit Manipulation',
          items: [
            {
              type: 'autogenerated',
              dirName: 'Algorithms/BitManipulation',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Data Structures',
      items: [
        {
          type: 'category',
          label: 'Basics',
          items: [
            {
              type: 'category',
              label: 'Binary Tree',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'DataStructures/Basic/BinaryTree',
                },
              ],
            },
            {
              type: 'category',
              label: 'B Tree',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'DataStructures/Basic/BTree',
                },
              ],
            },
            {
              type: 'category',
              label: 'Linked List',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'DataStructures/Basic/LinkedList',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Advanced',
          items: [
            {
              type: 'autogenerated',
              dirName: 'DataStructures/Advanced',
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Programming Languages',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Language',
        },
      ],
    },
  ],
  Stories: [
    {
      type: 'autogenerated',
      dirName: 'Stories',
    },
  ],
  MachineLearning: [
    {
      type: 'autogenerated',
      dirName: 'MachineLearning',
    },
  ],
};
