/**
 * Copyright (c) 2017-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

module.exports = {
  Algorithms: [
    {
      type: "category",
      label: "Sorting",
      collapsed: false,
      items: [{
        type: "autogenerated",
        dirName: "Algorithms/Sorting"
      }]
    },
    {
      type: "category", 
      label: "Backtracking",
      items: [
        "Algorithms/Backtracking/Introduction",
        "Algorithms/Backtracking/Permutation",
        "Algorithms/Backtracking/ExpressionPuzzle",
        "Algorithms/Backtracking/ConfusingNumber"
      ]
    },
    {
      type: "category",
      label: "Graph",
      items: [{
        type: "autogenerated",
        dirName: "Algorithms/Graph"
      }]
    },
    {
      type: "category",
      label: "Dynamic Programming",
      items: [
        {
          type: "category",
          label: "Coordinate Based",
          items: [{
            type: "autogenerated",
            dirName: "Algorithms/DynamicProgramming/Coordinate"
          }]
        }
      ]
    },
    {
      type: "category",
      label: "Sliding Window",
      items: [{
        type: "autogenerated",
        dirName: "Algorithms/SlidingWindow"
      }]
    },
    {
      type: "category",
      label: "Interval",
      items: [{
        type: "autogenerated",
        dirName: "Algorithms/Interval"
      }]
    },
    {
      type: "category",
      label: "Bit Manipulation",
      items: [{
        type: "autogenerated",
        dirName: "Algorithms/BitManipulation"
      }]
    }
  ],
  "Data Structure": [
    {
      type: "category",
      label: "Basics",
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Binary Tree",
          items: [
            "DataStructures/Basic/BinaryTree/Definitions&&Properties",
            "DataStructures/Basic/BinaryTree/BSTTraversals", 
            "DataStructures/Basic/BinaryTree/BSTOperations",
            {
              type: "category",
              label: "Common Problems",
              items: [{
                type: "autogenerated",
                dirName: "DataStructures/Basic/BinaryTree/CommonProblems"
              }]
            }
          ]
        },
        {
          type: "category",
          label: "B Tree",
          items: [{
            type: "autogenerated",
            dirName: "DataStructures/Basic/BTree"
          }]
        },
        {
          type: "category",
          label: "Linked List",
          items: [{
            type: "autogenerated",
            dirName: "DataStructures/Basic/LinkedList"
          }]
        }
      ]
    },
    {
      collapsed: false,
      type: "category",
      label: "Advanced",
      items: [{
        type: "autogenerated",
        dirName: "DataStructures/Advanced"
      }]
    }
  ],
  Applications: [
    {
      type: "category", 
      label: "Case Studies",
      collapsed: false,
      items: ["Applications/ReactFiber/index"]
    },
    {
      type: "category",
      label: "Language",
      items: [{
        type: "autogenerated",
        dirName: "Applications/Language"
      }]
    }
  ]
};
